http:
  routers:
    ollama:
      rule: "Host(`ollama.home.arpa`)"
      entryPoints:
        - web
      service: ollama

  services:
    ollama:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "http://host.docker.internal:11434"
